### ISSUE TITLE
Emoji cursor goes away below bottom of page

### ISSUE THREAD

**Issue by bporter816** [ashika-verma/ashika-verma.github.io#13]
One way to fix this could be to set the min height of the page to `100svh`.
![image](https://github.com/ashika-verma/ashika-verma.github.io/assets/20712582/38c953d9-4e32-41a0-b255-ca5cb7d746a2)![image](https://github.com/ashika-verma/ashika-verma.github.io/assets/20712582/63903571-14c9-47ab-a301-4f4103c890fc)

**Comment by ashika-verma** [comment]
fixed in: 5fd7f7cae59ee79e06dea1b10e1f94c7612553f9
